YTI-1593 Child organizations
VRK-YTI/yti-groupmanagement pull request #19
Opened 2021-11-23 08:55 UTC by kkyttala

2021-12-07 06:29 UTC, jukkah requested changes

2021-12-07 06:29 UTC, jukkah commented on frontend/po/fi.po
> +msgid "Parent organization"
This should be in other .po files too?

2021-12-07 06:29 UTC, jukkah commented on frontend/po/en.po
> +msgid "Add child organization"
These should be in template.pot too.

2021-12-08 07:42 UTC, jukkah approved these changes

2021-12-17 06:22 UTC, jukkah approved these changes

2021-12-17 06:23 UTC, topirissanen-atoz approved these changes

2021-12-20 14:50 UTC, jukkah approved these changes

2021-12-22 13:05 UTC, merged